/*
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
*/

// function findTheDifference(s: string, t: string): string {
//   const tChars: {[char: string]: number} = {};
//   const sChars: {[char: string]: number} = {};
//   for (let i = 0; i < t.length; i++) {
//     if (Object.keys(tChars).includes(t[i])) {
//       tChars[t[i]] += 1;
//     } else {
//       tChars[t[i]] = 1;
//     }
//     if (i < (t.length - 1)) {
//       if (Object.keys(sChars).includes(s[i])) {
//         sChars[s[i]] += 1;
//       } else {
//         sChars[s[i]] = 1;
//       }
//     }
//   }

//   for (const key of Object.keys(tChars)) {
//     const kol = tChars[key];
//     const kol1 = Object.keys(sChars).includes(key) ? sChars[key] : 0;

//     if (kol > kol1) {
//       return key;
//     }
//   }
//   return '';
// };

function findTheDifference(s: string, t: string): string {
  let diff = t.charCodeAt(t.length - 1);
  for (let i = 0; i < s.length; i++) {
    diff += t.charCodeAt(i) - s.charCodeAt(i);
  }
  return String.fromCharCode(diff);
}

let s = "abcd";
let t = "abcda";

const findTheDifferenceRes = findTheDifference(s, t);
console.log(findTheDifferenceRes);
